### ISSUE TITLE
优化prometheus.yaml提议

### ISSUE THREAD

**Issue by dong9205** [starsliao/ConsulManager#3]
源内容
```yaml
    params:
      module: [http_2xx]
```

目标内容
```yaml
 relabel_configs:
      - source_labels: [__meta_consul_service_metadata_module]
        target_label: __param_module
```

这样就可以省略写多个promteheus的job了，将需要用的blackbox module作为tag注册进consul, 然后prometheus进行label 替换为param参数.
